In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings

from matplotlib.pyplot import hist 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

In [2]:
train = pd.read_csv("C:/Users/USER/Downloads/train_users_2.csv/train_users_2.csv")
test = pd.read_csv("C:/Users/USER/Downloads/test_users.csv/test_users.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213451 entries, 0 to 213450
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       213451 non-null  object
 1   date_account_created     213451 non-null  object
 2   timestamp_first_active   213451 non-null  int64
 3   date_first_booking       88908 non-null   object
 4   gender                   213451 non-null  object
 5   age                      125461 non-null  float64
 6   signup_method            213451 non-null  object
 7   signup_flow              213451 non-null  int64
 8   language                 213451 non-null  object
 9   affiliate_channel        213451 non-null  object
 10  affiliate_provider       213451 non-null  object
 11  first_affiliate_tracked  207386 non-null  object
 12  signup_app               213451 non-null  object
 13  first_device_type        213451 non-null  object
 14  first_browser            213451 non-null  object
 15  country_destination      213451 non-null  object
dtypes: float64(1), int64(2), object(13)
memory usage: 26.1+ MB

In [4]:
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [5]:
X_train = train.drop(['date_first_booking', 'country_destination'], axis=1)
X_test = test.drop(['date_first_booking'], axis=1)

In [6]:
train['country_destination'].unique()

array(['NDF', 'US', 'other', 'FR', 'CA', 'GB', 'ES', 'IT', 'PT', 'NL',
       'DE', 'AU'], dtype=object)

In [7]:
train['country_destination'] = train['country_destination'].replace({'NDF':1,'US':2,'other':3, 'FR':4, 'CA':5, 'GB':6, 'ES':7, 'IT':8, 'PT':9, 'NL':10,'DE':11,'AU':12})
train.head()

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,2010-06-28,20090319043255,NaN,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,1
1,820tgsjxq7,2011-05-25,20090523174809,NaN,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,1
2,4ft3gnwmtx,2010-09-28,20090609231247,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,2
3,bjjt8pjhuk,2011-12-05,20091031060129,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,3
4,87mebub9p4,2010-09-14,20091208061105,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2

In [8]:
X=pd.concat((X_train, X_test), axis=0, ignore_index=True)
X.shape

(275547, 14)

In [9]:
X.head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,gxn3p5htnn,2010-06-28,20090319043255,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome
1,820tgsjxq7,2011-05-25,20090523174809,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome
2,4ft3gnwmtx,2010-09-28,20090609231247,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE
3,bjjt8pjhuk,2011-12-05,20091031060129,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox
4,87mebub9p4,2010-09-14,20091208061105,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome

In [10]:
X['gender'].unique()

array(['-unknown-', 'MALE', 'FEMALE', 'OTHER'], dtype=object)

In [11]:
X['gender'] = X['gender'].replace({'-unknown-':1 , 'MALE':2 , 'FEMALE':3 , 'OTHER':4})

In [12]:
X['signup_method'].unique()

array(['facebook', 'basic', 'google', 'weibo'], dtype=object)

In [13]:
X['signup_method'] = X['signup_method'].replace({'facebook':1 , 'basic':2 , 'google':3 , 'weibo':4})

In [14]:
X['language'].unique()

array(['en', 'fr', 'de', 'es', 'it', 'pt', 'zh', 'ko', 'ja', 'ru', 'pl',
       'el', 'sv', 'nl', 'hu', 'da', 'id', 'fi', 'no', 'tr', 'th', 'cs',
       'hr', 'ca', 'is', '-unknown-'], dtype=object)

In [15]:
X['language'] = X['language'].replace({'en':1 , 'fr':2, 'de':3, 'es':4, 'it':5, 'pt':6, 'zh':7, 'ko':8, 'ja':9, 'ru':10, 'pl':11,
       'el':12, 'sv':13, 'nl':14, 'hu':15, 'da':16, 'id':17, 'fi':18, 'no':19, 'tr':20, 'th':21, 'cs':22,
       'hr':23, 'ca':24, 'is':25, '-unknown-':26})

In [16]:
X['affiliate_channel'].unique()

array(['direct', 'seo', 'other', 'sem-non-brand', 'content', 'sem-brand',
       'remarketing', 'api'], dtype=object)

In [17]:
X['affiliate_channel'] = X['affiliate_channel'].replace({'direct':1, 'seo':2, 'other':3, 'sem-non-brand':4, 'content':5, 'sem-brand':6,
       'remarketing':7, 'api':8})

In [18]:
X['affiliate_provider'].unique()

array(['direct', 'google', 'other', 'craigslist', 'facebook', 'vast',
       'bing', 'meetup', 'facebook-open-graph', 'email-marketing',
       'yahoo', 'padmapper', 'gsp', 'wayn', 'naver', 'baidu', 'yandex',
       'daum'], dtype=object)

In [19]:
X['affiliate_provider'] = X['affiliate_provider'].replace({'direct':1, 'google':2, 'other':3, 'craigslist':4, 'facebook':5, 'vast':6,
       'bing':7, 'meetup':8, 'facebook-open-graph':9, 'email-marketing':10,
       'yahoo':11, 'padmapper':12, 'gsp':13, 'wayn':14 ,'naver':15, 'baidu':16, 'yandex':17,
       'daum':18})

In [20]:
X['first_affiliate_tracked'].unique()

array(['untracked', 'omg', nan, 'linked', 'tracked-other', 'product',
       'marketing', 'local ops'], dtype=object)

In [21]:
X['first_affiliate_tracked'] = X['first_affiliate_tracked'].replace({'untracked':1, 'omg':2, 'linked':3, 'tracked-other':4, 'product':5,
       'marketing':6, 'local ops':7})

In [22]:
X['signup_app'].unique()

array(['Web', 'Moweb', 'iOS', 'Android'], dtype=object)

In [23]:
X['signup_app'] = X['signup_app'].replace({'Web':1, 'Moweb':2, 'iOS':3, 'Android':4})

In [24]:
X['first_device_type'].unique()

array(['Mac Desktop', 'Windows Desktop', 'iPhone', 'Other/Unknown',
       'Desktop (Other)', 'Android Tablet', 'iPad', 'Android Phone',
       'SmartPhone (Other)'], dtype=object)

In [25]:
X['first_device_type'] = X['first_device_type'].replace({'Mac Desktop':1, 'Windows Desktop':2, 'iPhone':3, 'Other/Unknown':4,
       'Desktop (Other)':5, 'Android Tablet':6, 'iPad':7, 'Android Phone':8,
       'SmartPhone (Other)':9})

In [26]:
X['first_browser'].unique()

array(['Chrome', 'IE', 'Firefox', 'Safari', '-unknown-', 'Mobile Safari',
       'Chrome Mobile', 'RockMelt', 'Chromium', 'Android Browser',
       'AOL Explorer', 'Palm Pre web browser', 'Mobile Firefox', 'Opera',
       'TenFourFox', 'IE Mobile', 'Apple Mail', 'Silk', 'Camino', 'Arora',
       'BlackBerry Browser', 'SeaMonkey', 'Iron', 'Sogou Explorer',
       'IceWeasel', 'Opera Mini', 'SiteKiosk', 'Maxthon',
       'Kindle Browser', 'CoolNovo', 'Conkeror', 'wOSBrowser',
       'Google Earth', 'Crazy Browser', 'Mozilla', 'OmniWeb',
       'PS Vita browser', 'NetNewsWire', 'CometBird', 'Comodo Dragon',
       'Flock', 'Pale Moon', 'Avant Browser', 'Opera Mobile',
       'Yandex.Browser', 'TheWorld Browser', 'SlimBrowser', 'Epic',
       'Stainless', 'Googlebot', 'Outlook 2007', 'IceDragon', 'IBrowse',
       'Nintendo Browser', 'UC Browser'], dtype=object)

In [27]:
X['first_browser'] = X['first_browser'].replace({'Chrome':1, 'IE':2, 'Firefox':3, 'Safari':4, '-unknown-':5, 'Mobile Safari':6,
       'Chrome Mobile':7, 'RockMelt':8, 'Chromium':9, 'Android Browser':10,
       'AOL Explorer':11, 'Palm Pre web browser':12, 'Mobile Firefox':13, 'Opera':14,
       'TenFourFox':15, 'IE Mobile':16, 'Apple Mail':17, 'Silk':18, 'Camino':19, 'Arora':20,
       'BlackBerry Browser':21, 'SeaMonkey':22, 'Iron':23, 'Sogou Explorer':24,
       'IceWeasel':25, 'Opera Mini':26, 'SiteKiosk':27, 'Maxthon':28,
       'Kindle Browser':29, 'CoolNovo':30, 'Conkeror':31, 'wOSBrowser':32,
       'Google Earth':33, 'Crazy Browser':34, 'Mozilla':35, 'OmniWeb':36,
       'PS Vita browser':37, 'NetNewsWire':38, 'CometBird':39, 'Comodo Dragon':40,
       'Flock':41, 'Pale Moon':42, 'Avant Browser':43, 'Opera Mobile':44,
       'Yandex.Browser':45, 'TheWorld Browser':46, 'SlimBrowser':47, 'Epic':48,
       'Stainless':50, 'Googlebot':52, 'Outlook 2007':53, 'IceDragon':54, 'IBrowse':55,
       'Nintendo Browser':56, 'UC Browser':57})

In [28]:
X.head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,gxn3p5htnn,2010-06-28,20090319043255,1,NaN,1,0,1,1,1,1.0,1,1,1
1,820tgsjxq7,2011-05-25,20090523174809,2,38.0,1,0,1,2,2,1.0,1,1,1
2,4ft3gnwmtx,2010-09-28,20090609231247,3,56.0,2,3,1,1,1,1.0,1,2,2
3,bjjt8pjhuk,2011-12-05,20091031060129,3,42.0,1,0,1,1,1,1.0,1,1,3
4,87mebub9p4,2010-09-14,20091208061105,1,41.0,2,0,1,1,1,1.0,1,1,1

In [29]:
X.loc[X.age > 90, 'age'] = -1
X.loc[X.age < 13, 'age'] = -1
X['age'].describe()

count    158681.000000
mean         35.268066
std          12.392166
min          -1.000000
25%          28.000000
50%          33.000000
75%          41.000000
max          90.000000
Name: age, dtype: float64

In [30]:
X.loc[X.age.isnull(), 'age']=X.age.mean()

In [31]:
X.fillna(method='pad').head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,gxn3p5htnn,2010-06-28,20090319043255,1,35.268066,1,0,1,1,1,1.0,1,1,1
1,820tgsjxq7,2011-05-25,20090523174809,2,38.000000,1,0,1,2,2,1.0,1,1,1
2,4ft3gnwmtx,2010-09-28,20090609231247,3,56.000000,2,3,1,1,1,1.0,1,2,2
3,bjjt8pjhuk,2011-12-05,20091031060129,3,42.000000,1,0,1,1,1,1.0,1,1,3
4,87mebub9p4,2010-09-14,20091208061105,1,41.000000,2,0,1,1,1,1.0,1,1,1

In [32]:
y_des = train[['country_destination']]
y_des['country_destination'] = y_des['country_destination'].replace({'NDF':1,'US':2,'other':3, 'FR':4, 'CA':5, 'GB':6, 'ES':7, 'IT':8, 'PT':9, 'NL':10,'DE':11,'AU':12})

C:\Users\USER\AppData\Local\Temp\ipykernel_11972\3567434037.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_des['country_destination'] = y_des['country_destination'].replace({'NDF':1,'US':2,'other':3, 'FR':4, 'CA':5, 'GB':6, 'ES':7, 'IT':8, 'PT':9, 'NL':10,'DE':11,'AU':12})

In [33]:
y_des.head()

   country_destination
0                    1
1                    1
2                    2
3                    3
4                    2

In [34]:
X.isna().sum()

id                            0
date_account_created          0
timestamp_first_active        0
gender                        0
age                           0
signup_method                 0
signup_flow                   0
language                      0
affiliate_channel             0
affiliate_provider            0
first_affiliate_tracked    6085
signup_app                    0
first_device_type             0
first_browser                 0
dtype: int64

In [35]:
X.loc[X.age > 90, 'age'] = -1
X.loc[X.age < 13, 'age'] = -1
X['age'].describe()

count    275547.000000
mean         35.268066
std           9.403971
min          -1.000000
25%          31.000000
50%          35.268066
75%          35.268066
max          90.000000
Name: age, dtype: float64

In [36]:
X.loc[X.age.isnull(), 'age']=X.age.mean()

In [37]:
X.loc[X.first_affiliate_tracked.isnull(), 'first_affiliate_tracked']=X.first_affiliate_tracked.mean()

In [38]:
dac = np.vstack(
    X.date_account_created.astype(str).apply(
        lambda x: list(map(int, x.split('-')))
    ).values
)
X['dac_year'] = dac[:, 0]
X['dac_month'] = dac[:, 1]
X['dac_day'] = dac[:, 2]
X = X.drop(['date_account_created'], axis=1)
X.head()

,id,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,dac_year,dac_month,dac_day
0,gxn3p5htnn,20090319043255,1,35.268066,1,0,1,1,1,1.0,1,1,1,2010,6,28
1,820tgsjxq7,20090523174809,2,38.000000,1,0,1,2,2,1.0,1,1,1,2011,5,25
2,4ft3gnwmtx,20090609231247,3,56.000000,2,3,1,1,1,1.0,1,2,2,2010,9,28
3,bjjt8pjhuk,20091031060129,3,42.000000,1,0,1,1,1,1.0,1,1,3,2011,12,5
4,87mebub9p4,20091208061105,1,41.000000,2,0,1,1,1,1.0,1,1,1,2010,9,14

In [39]:
X.isna().sum()

id                         0
timestamp_first_active     0
gender                     0
age                        0
signup_method              0
signup_flow                0
language                   0
affiliate_channel          0
affiliate_provider         0
first_affiliate_tracked    0
signup_app                 0
first_device_type          0
first_browser              0
dac_year                   0
dac_month                  0
dac_day                    0
dtype: int64

In [40]:
for i in X.columns:
    print(i)

id
timestamp_first_active
gender
age
signup_method
signup_flow
language
affiliate_channel
affiliate_provider
first_affiliate_tracked
signup_app
first_device_type
first_browser
dac_year
dac_month
dac_day

In [41]:
np.nan_to_num(X)

array([['gxn3p5htnn', 20090319043255, 1, ..., 2010, 6, 28],
       ['820tgsjxq7', 20090523174809, 2, ..., 2011, 5, 25],
       ['4ft3gnwmtx', 20090609231247, 3, ..., 2010, 9, 28],
       ...,
       ['fa6260ziny', 20140930235408, 1, ..., 2014, 9, 30],
       ['87k0fy4ugm', 20140930235430, 1, ..., 2014, 9, 30],
       ['9uqfg8txu3', 20140930235901, 3, ..., 2014, 9, 30]], dtype=object)

In [42]:
corr_matrix = X.corr()
corr_matrix.style.background_gradient(cmap = 'RdYlGn')

## Splitting the data into train and test

In [43]:
X_train = X.iloc[:len(train), :]          #selection of specific columns
X_test = X.iloc[len(train):, :]           #selection of specific solumns
X_train = X_train.drop(['id'], axis=1)
X_train.shape
X_test = X_test.drop(['id'], axis=1)

In [44]:
le = LabelEncoder()
y_trans = le.fit_transform(y_des)
y_trans.shape

C:\Users\USER\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

(213451,)

In [45]:
dtrain, dtest, train_label, test_label = train_test_split(X_train, y_trans, test_size = 0.8, random_state = 817)

In [46]:
train_label.shape

(42690,)

In [47]:
dtrain.shape

(42690, 15)

In [48]:
test.shape

(62096, 15)

## Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(dtrain, train_label)
pred_log=logreg.predict(dtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(test_label, pred_log))

0.5829726928279877

## Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=20, n_estimators=100)
rfc.fit(dtrain , train_label)
pred = rfc.predict(dtest)
print(accuracy_score(test_label, pred))

0.6176995918271736

## Decision Tree

In [51]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=10)
dtc.fit(dtrain , train_label)
pred = dtc.predict(dtest)
print(accuracy_score(test_label, pred))

0.62025286804364

## XgBoost

In [52]:
from xgboost.sklearn import XGBClassifier
xgb = XGBClassifier(max_depth=4, learning_rate=0.03, n_estimators=100,
                     subsample=0.6, colsample_bytree=0.6, seed=40)
xgb.fit(dtrain , train_label)
pred = xgb.predict(dtest) 
print(accuracy_score(test_label, pred))

0.6316489128079597

## Hyperparameter tuning

In [53]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [54]:
model_params = {
    'svm':{
        'model': svm.SVC(gamma = 'auto'),
        'params': {
            'C': [1,10,20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params':{
            'n_estimators': [1,5,10]     #argument in randomforest clssifier
        }`
    },
    'logistic_regression':{
        'model': LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [57]:
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    "C": [1,10,20],
    "kernel": ['rbf', 'linear']},
                       cv = 5,
                       return_train_score = False,
                       n_iter = 2)                   #we are trying 2 combinations
rs.fit(dtrain, train_label)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

  param_C param_kernel  mean_test_score
0      10          rbf         0.585477
1       1          rbf         0.585477